# Generated by Django 4.2.8 on 2024-03-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='crated',
            new_name='created',
        ),
    ]
