# Generated by Django 4.2.8 on 2024-02-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='created_time',
            new_name='created_timestamp',
        ),
    ]
